name: mbespc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - GDAL==3.7.2
  - numpy==1.23.5
  - pyproj==3.4.1
  - pdal=2.6.0
  - pip
  - pip:
    - pytest
    - click==8.1.3
    - laspy
    - rasterio==1.3.9
    - pdal
    - git+https://github.com/ausseabed/qajson.git
