name: mbespc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - GDAL==3.6.2
  - tiledb==2.13.2
  - numpy==1.23.5
  - pyproj==3.4.1
  - pdal=2.5.0
  - python-pdal==3.2.2
  - rasterio==1.3.6
  - pip
  - pip:
    - pytest
    - click==8.1.3
    - laspy
    - git+https://github.com/ausseabed/qajson.git
